name: ci-workflow
on:
    push: 
        branches: ['**']
    pull_request: 
        branches: 
            - main
        types: 
            - opened
jobs:
    ci-job:
        runs-on: ubuntu-latest
        steps:
            #following steps are for testing/learning purpose
            - name: Help
              run: echo "Allah Please Help Me"
            - name: Repository Name
              run: echo ${{github.repository}}
            - name: Branch Details
              run: echo ${{github.ref_name}}
            - name: Committer
              run: echo ${{github.actor}}

    